name: Post release to slack

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Instal dependencies
        if: steps.cache-node-modules.outputs.cache.hit != 'true'
        run: yarn install

      - name: build app
        run: yarn run build

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: ${{ github.event.repository.name }}-${{ steps.tagName.outputs.tag }}.zip
          directory: './build'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: ${{ github.event.repository.name }}-${{  steps.tagName.outputs.tag }}.zip
          channel: extension_releases
